### ISSUE TITLE
base on fasthttp?

### ISSUE THREAD

**Issue by dalu** [get-ion/issues-v1#11]
I see you're a big contributor to iris. I'm not a fan of the person who owns it, on the contrary, because of his policy on issues and you're probably aware of the drama.

Anyhow, I wonder why aren't you basing a new project on fasthttp rather than basing it on net/http?

Why, you ask?

https://www.techempower.com/benchmarks/#section=data-r14&hw=ph&test=fortune

It seems to perform rather well.
I mean.. there's gin and it essentially does what ion does. And there are more .Use etc. routers out there with input binding and json serialization contexts (express-like api). There's nothing new on the table.

I don't mean to be negative, but realistic.

**Comment by rebootcode** [comment]
@dalu - there is no point in creating new. Also, people at Google, Microsoft, and Linux are arrogant too, that doesn't mean, you stop using them.

The person has built an amazing product and we should appreciate, things will change slowly, but "appreciation" and "love" turns thing.

Go ahead and appreciate the hard work, I am sure, rest will follow up :+1:

**Comment by dalu** [comment]
I'm non interested in a discussion about kataras or w/e he's spelled or iris.
But I will comment nevertheless.
When someone STEALS from other people and calls this his own work then there is NOTHING TO APPRECIATE. Even after they explicitly tell him to stop.
When someone edits issues created by users to make it work as if he created the isses (and yes this happened to me) then there IS NOTHING TO APPRECIATE.
And you don't know the concept of respect, I do.
And I for one will not support a liar and a thief, because that's what kataras is.

THIS ISSUE HERE, however IS NOT ABOUT IRIS OR KATARAS.
So if you want to continue this discussion I suggest you continue on your own, because I don't have time to waste on liars and thieves and by that I don't mean you, because I don't know you and have not witnessed theft or lies yet.

So unless you have nothing worthwhile to contribute please refrain from posting on this issue.
Actually I already regret creating this question.

I know that I won't be using ion or iris.

**Comment by rebootcode** [comment]
`and by that I don't mean you, because I don't know you and have not witnessed theft or lies yet.` - @dalu 

You must be stupid.
