### ISSUE TITLE
Is ion dead ?

### ISSUE THREAD

**Issue by waghanza** [get-ion/issues-v1#12]
Hi @hiveminded,

I've tried to introduce `ion` in https://github.com/the-benchmarker/web-frameworks/pull/536 to compete with other `go` frameworks.

Is `ion` maintained ?

Regards,

**Comment by rebootcode** [comment]
head over to https://github.com/kataras/iris

**Comment by waghanza** [comment]
you mean that `iris` is the new `ion` ?

**Comment by rebootcode** [comment]
ion was fork of IRIS, but ion is no more maintained and IRIS is getting updated daily.

**Comment by waghanza** [comment]
ok, thanks
