### ISSUE TITLE
Remote Address Logging via Cloudflare

### ISSUE THREAD

**Issue by rebootcode** [get-ion/issues-v1#2]
Hi, `ctx.RemoteAddr()` failing while on cloudflare - getting cloudflare IP address and the solution to it is below :- any suggestion please recommend.

context/context.go @ line no. L1057-1081

Below 2 request headers can be checked if present in cloudflare :- 

```
header := ctx.GetHeader("HTTP-CF-CONNECTING-IP")
	realIP := strings.TrimSpace(header)
	if realIP != "" {
		return realIP
	}
```

Where header `HTTP-CF-CONNECTING-IP` represents cloudflare ways to get connecting client IP Address.

also, i am new to get-ion , so wanted to know, if `ctx.request` is actually `http.Request` for fetching IP-Address ?

```
addr := strings.TrimSpace(ctx.request.RemoteAddr) 
```

Thanks and Kudos for maintaining it.

**Comment by hiveminded** [comment]
Hi @rebootcode ,

> also, i am new to get-ion , so wanted to know, if ctx.request is actually http.Request for fetching IP-Address ?

Yes by calling the `ctx.Request()` you get the same `*http.Request` as you used to with `net/http`.

> Below 2 request headers can be checked if present in cloudflare :-...

We can make that change to reflect the cloudflare's usage but don't forget that
you can also override context's functions with your own customized, see [here](https://github.com/get-ion/ion/blob/master/_examples/routing/custom-context/method-overriding/main.go#L46).

**Comment by rebootcode** [comment]
Great! Thanks

**Comment by hiveminded** [comment]
You're welcome, now the `RemoteAddr` respects the `HTTP_CF_CONNECTING_IP ` header too, as you suggested.

**Comment by hiveminded** [comment]
@rebootcode this could be a security leak for some types of applications so I introduced a new feature that you can enable/disable /add header names that are responsible to parse the client's IP via `context.RemoteAddr()`.  _"HTTP_CF_CONNECTING_IP"_ is disabled by-default.



So, you have to change your code and add the configuration option `WithRemoteAddrHeader` to the `Run` method, i.e:

```go
app.Run([...], [...], ion.WithRemoteAddrHeader("HTTP_CF_CONNECTING_IP"))
```

Navigate to https://github.com/get-ion/issues-v1/issues/5 for more.
