### ISSUE TITLE
Useragent and Referer

### ISSUE THREAD

**Issue by rebootcode** [get-ion/issues-v1#3]
Hi,

Is there ways, where one can also log "Useragent" and "Referer" like below :- 

```
ctx.UserAgent()
```
or
```
ctx.Referer()
```

as both are available in default "net/http" package.

**Comment by hiveminded** [comment]
@rebootcode Hi,

`http.Request` is available inside the `Context`. Use `ctx.Request().UserAgent()` and `ctx.Request().Referer()` respectfully.
