### ISSUE TITLE
[ How to ? ] Attaching static assets like CSS, fonts and JS

### ISSUE THREAD

**Issue by rebootcode** [get-ion/issues-v1#4]
How can one attach static assets like `css`, `fonts` or `js` file. 

Currently , I am using CDN and they worked fine, but i need to load some of the css from template directory. Is it possible with "ion"

Thanks

**Comment by hiveminded** [comment]
Absolutely, please take a look at the [file-server/basic](https://github.com/get-ion/ion/tree/master/_examples/file-server/basic) example.
