### ISSUE TITLE
CSRF Protection

### ISSUE THREAD

**Issue by rebootcode** [get-ion/issues-v1#6]
I could not find any inbuilt CSRF protection module ? Does `ion` has any ? or One has to create them on fly with `session` module ?

**Comment by hiveminded** [comment]
> Does `ion` has any?

_ion_ has everything that `net/http` has too. For example I did a quick search and I found [nosurf](https://github.com/justinas/nosurf) which is a library for CSRF protection. It requires the `*http.Request` to be passed on its functions, you have access to that `*http.Request` via `ctx.Request()` so you can use that or any other library you used to use before _ion_.
