### ISSUE TITLE
WebSocket broadcast

### ISSUE THREAD

**Issue by simpleblack** [get-ion/issues-v1#7]
I have question
I want used room and broadcast

I guess source.
but not working `func To` return only Emit
how can room in broadcast?
```
Room := "room1"
c.Join(Room)
c.To(websocket.Broadcast).To(Room).Emit("chat", "room:" + Room)
```

**Comment by rebootcode** [comment]
Have you tried this : https://github.com/get-ion/websocket/blob/master/_examples/connectionlist/main.go#L47

**Comment by simpleblack** [comment]
@rebootcode 
I tried this example, but exmple is room in every emit `c.To(myChatRoom)`.
I want room in except me emit

example socket.io
``` javascript
socket.broadcast.to(room).emit('chat', data);
```

Is there no other way?
Thanks.

**Comment by Dexus** [comment]
The fix need to be done here: https://github.com/get-ion/websocket/blob/master/server.go#L335

**Comment by simpleblack** [comment]
@Dexus 
I try.
Thank you.

**Comment by rebootcode** [comment]
@simpleblack do share your snippets, will love to see, how you have made for multi-broadcasting.

**Comment by simpleblack** [comment]
@rebootcode 
now not make multi-broadcasting.
I can share my snippets if i make this.
