### ISSUE TITLE
File based session storage

### ISSUE THREAD

**Issue by rebootcode** [get-ion/issues-v1#8]
Hi, I see "iris" is back up with v8.x . Congratulation to team and @hiveminded 

Does Iris / get-ion supports `file` based session ? Memory based session and database sessions are not optimal requirement for scaling up.

If it's not already there, is it hard to implement them ? Please share some light so that , i can try implementing them.

Thanks

**Comment by hiveminded** [comment]
Resolved on https://github.com/kataras/iris/issues/702
