### ISSUE TITLE
There is an error in get-ion/_examples/hello-world

### ISSUE THREAD

**Issue by youknow98** [get-ion/issues-v1#9]
liujie@liujie-VPCEA1S4C ~/GoWorkSpace/src/github.com/get-ion/ion/_examples/hello-world $ go run main.go
# github.com/get-ion/ion/core/host
../../core/host/task.go:24: cannot use h.Supervisor.manuallyTLS (type bool) as type string in argument to netutil.ResolveScheme
../../core/host/task.go:25: undefined: netutil.ResolveURL
# github.com/get-ion/ion/core/router
../../core/router/path.go:158: undefined: netutil.ResolveSchemeFromVHost

why???

**Comment by hiveminded** [comment]
The build has succeed, there are no errors like you're describing, see by yourself:

The [ResolveScheme](https://github.com/get-ion/ion/blob/master/core/netutil/addr.go#L200) accepts a boolean not a string. The `netuitl.ResolveSchemeFromVHost` does not even exist.


I think here is an error in your local machine not in the framework, please try to delete the get-ion folder and re-download it (` go get -u github.com/get-ion/ion` ).
